service:
  host : 127.0.0.1
  #host : 124.222.131.109
  port : 9002


mysql:
  host: 124.222.131.109
  port: 23306
  dbname: mall
  username: root
  password: lijialang666
  charset: utf8mb4


redis:
  host: 124.222.131.109
  port: 26379
  password: lijialang666

jaeger:
  host: 124.222.131.109
  port: 24317


static:
  avatarPath: ./data/static/avatar