version: '3.8'


services:

  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lijialang666!
      MYSQL_DATABASE: mall
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

  redis:
    image: redis:latest
    container_name: redis
    init: true
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis/data:/data
    environment:
      REDIS_PASSWORD: lijialang666
    command: ["redis-server", "--requirepass", "lijialang666"]



  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    volumes:
      - ./data/jaeger/logs:/var/log/jaeger       # 挂载日志目录
      - ./data/jaeger/data:/var/lib/jaeger       # 挂载数据目录
