service:
  host : 127.0.0.1
  #host : 124.222.131.109
  port : 9003


mysql:
  host: 124.222.131.109
  port: 23306
  dbname: mall
  username: root
  password: lijialang666
  charset: utf8mb4

elasticSearch:
  host: 192.168.40.134
  port: 8080
  username: "elastic",
  password: "=Bq7JViaHHw_hdCabKVv",
  certificate_fingerprint: "039e813e2fc4847f3863ab90b05fbfa76adaaffe236ba9b26dac41b2136723fe",