#生成结构体
#go install github.com/Icemap/yaml2go-cli@latest
#yaml2go-cli -i config/yaml/common.yaml -o config/generation.go -p config

nacos:
  host : "192.168.134.128"
  port :  8848

# 日志
log:
  level: "debug"
  basePath: ./logs/app.log
  maxAge: 30
  maxBackups: 60
  maxSize: 200
  mode: develop
  #prod 生产环境（production environment）模式


jaeger:
  host: "192.168.134.128"
  port: 4318