service:
  host : 127.0.0.1
  #host : 192.168.227.172
  port : 9001


mysql:
  host: 192.168.227.172
  port: 23306
  dbname: mall
  username: root
  password: lijialang666
  charset: utf8mb4


redis:
  host: 192.168.227.172
  port: 26379
  password: lijialang666

jaeger:
  host: 192.168.134.128
  port: 24318


# 业务

phone:


email:
  addresses:
  email:
  host :
  name: tiktok_mall
  password: lijialang666
  port: 465
  expiration_time : 300s   # 邮箱有效期 300 秒


photoCaptcha:
  height: 80          # 验证码图片的高度
  width: 240          # 验证码图片的宽度
  length: 5           # 验证码字符的长度
  maxSkew: 0.7        # 数字的最大倾斜角度
  dotCount: 80        # 图片背景中的混淆点数量
  expire: 180s

