service:
  host : 127.0.0.1
  #host : 124.222.131.109
  port : 9001


mysql:
  host: 124.222.131.109
  port: 23306
  dbname: mall
  username: root
  password: lijialang666
  charset: utf8mb4


redis:
  host: 124.222.131.109
  port: 26379
  password: lijialang666

jaeger:
  host: 124.222.131.109
  port: 24317


# 业务

phone:
  accessKeyId: "LTAI5t8LkfrqgiBhXrLECUXV"
  accessKeySecret: "RGvYAmyeXMy88HuT4gqj4YVyl5bsNI"
  regionId: ""
  sendInterval: 60s   # 发送间隔


email:
  addresses:
  email:
  host :
  name: tiktok_mall
  password: lijialang666
  port: 465
  expiration_time: 300s   # 邮箱有效期 300 秒
  sendInterval: 60s   # 发送间隔


photoCaptcha:
  height: 80          # 验证码图片的高度
  width: 240          # 验证码图片的宽度
  length: 5           # 验证码字符的长度
  maxSkew: 0.7        # 数字的最大倾斜角度
  dotCount: 80        # 图片背景中的混淆点数量
  expire: 180s


jwt:
  accessExpireTime: 60m
  refreshExpireTime: 168h
  accessSecret: tiktok_mall_access
  refreshSecret:  tiktok_mall_refresh
  issuer: zty


password:
  ErrorLimit: 8   # 密码锁定次数
  ErrorLockTime: 30m # 锁定时间