service:
  host : 127.0.0.1
  #host : 124.222.131.109
  port : 8080

jaeger:
  host: 124.222.131.109
  port: 24317


# 业务
role:
  model: ./config/casbin/dataModel.conf
  policy: ./config/casbin/policy.csv

jwt:
  accessExpireTime: 60m
  refreshExpireTime: 168h
  accessSecret: tiktok_mall_access
  refreshSecret:  tiktok_mall_refresh
  issuer: zty

visitLimit:
  rateLimitInterval: 0.5s # 令牌投放速率
  rateLimitCap: 30  # 限流的最大容量



