service:
  host : 127.0.0.1
  #host : 192.168.227.172
  port : 28080


mysql:
  host: 192.168.227.172
  port: 23306
  dbname: mall
  username: root
  password: lijialang666
  charset: utf8mb4


redis:
  host: 192.168.227.172
  port: 26379
  password: lijialang666

jaeger:
  host: 192.168.134.128
  port: 24318


# 业务
role:
  model: ./config/casbin/dataModel.conf
  policy: ./config/casbin/policy.csv

jwt:
  accessExpireTime: 60m
  refreshExpireTime: 168h
  accessSecret: tiktok_mall_access
  refreshSecret:  tiktok_mall_refresh
  issuer: zty

visitLimit:
  rateLimitInterval: 0.5s # 令牌投放速率
  rateLimitCap: 30  # 限流的最大容量

password:
  ErrorLimit: 8   # 密码锁定次数
  ErrorLockTime: 30m # 锁定时间

